// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://khceqzcynwuvuvwgfxwt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtoY2VxemN5bnd1dnV2d2dmeHd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MjQ5OTAsImV4cCI6MjA3NDMwMDk5MH0.zH8hrrHIUhu3JWNVqhHXEAFMmc8TOmyb0OojzJ1nsYw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});